version: "3.8"

services:
  react.frontend:
    container_name: react.frontend
    image: react.frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000